= 5 Stopping and Continuing
:toc: left

* The principal purposes of using a debugger are so that you can stop your
  program before it terminates; or so that, if your program runs into trouble,
  you can investigate and find out why.

'''

* Inside gdb, your program may stop for any of several reasons, such as a
  signal, a breakpoint, or reaching a new line after a gdb command such as
  `step`.
* You may then examine and change variables, set new breakpoints or remove old
  ones, and then continue execution.
* Usually, the messages shown by gdb provide ample explanation of the status
  of your program -- but you can also explicitly request this information at
  any time.

'''

`info program`::
* Display information about the status of your program: whether it is running
  or not, what process it is, and why it stopped.

== 5.1 Breakpoints, Watchpoints, and Catchpoints

* A _breakpoint_ makes your program stop whenever a certain point in the
  program is reached.
* For each breakpoint, you can add conditions to control in finer detail
  whether your program stops.
* You can set breakpoints with the `break` command and its variants (see
  Section 5.1.1 [Setting Breakpoints], page 58), to specify the place where
  your program should stop by line number, function name or exact address in
  the program.

'''

* On some systems, you can set breakpoints in shared libraries before the
  executable is run.

'''

* A _watchpoint_ is a special breakpoint that stops your program when the
  value of an expression changes.
* The expression may be a value of a variable, or it could involve values of
  one or more variables combined by operators, such as \'``a + b``'.
* This is sometimes called _data breakpoints_.
* You must use a different command to set watchpoints (see Section 5.1.2
  [Setting Watchpoints], page 66), but aside from that, you can manage a
  watchpoint like any other breakpoint: you enable, disable, and delete both
  breakpoints and watchpoints using the same commands.

'''

* You can arrange to have values from your program displayed automatically
  whenever gdb stops at a breakpoint.
* See Section 10.8 [Automatic Display], page 155.

'''

* A _catchpoint_ is another special breakpoint that stops your program when a
  certain kind of event occurs, such as the throwing of a C++ exception or the
  loading of a library.
* As with watchpoints, you use a different command to set a catchpoint (see
  Section 5.1.3 [Setting Catchpoints], page 69), but aside from that, you can
  manage a catchpoint like any other breakpoint.
* (To stop when your program receives a signal, use the `handle` command; see
  Section 5.4 [Signals], page 89.)

'''

* gdb assigns a number to each breakpoint, watchpoint, or catchpoint when you
  create it; these numbers are successive integers starting with one.
* In many of the commands for controlling various features of breakpoints you
  use the breakpoint number to say which breakpoint you want to change.
* Each breakpoint may be enabled or disabled; if disabled, it has no effect on
  your program until you enable it again.

'''

* Some gdb commands accept a space-separated list of breakpoints on which to
  operate.
* A list element can be either a single breakpoint number, like \'``5``', or a
  range of such numbers, like \'``5-7``'.
* When a breakpoint list is given to a command, all breakpoints in that list
  are operated on.

=== 5.1.1 Setting Breakpoints

* Breakpoints are set with the `break` command (abbreviated `b`).
* The debugger convenience variable \'``$bpnum``' records the number of the
  breakpoint you've set most recently:

....
(gdb) b main
Breakpoint 1 at 0x11c6: file zeoes.c, line 24.
(gdb) p $bpnum
$1 = 1
....

* A breakpoint may be mapped to multiple code locations for example with
  inlined functions, Ada generics, C++ templates or overloaded function names.
* gdb then indicates the number of code locations in the breakpoint command
  output:

....
(gdb) b some_func
Breakpoint 2 at 0x1179: some_func. (3 locations)
(gdb) p $bpnum
$2 = 2
(gdb)
....

* When your program stops on a breakpoint, the convenience variables
  \'``$_hit_bpnum``' and \'``$_hit_locno``' are respectively set to the number
  of the encountered breakpoint and the number of the breakpoint's code
  location:

....
Thread 1 "zeoes" hit Breakpoint 2.1, some_func () at zeoes.c:8
8 printf("some func\n");
(gdb) p $_hit_bpnum
$5 = 2
(gdb) p $_hit_locno
$6 = 1
(gdb)
....

* Note that \'``$_hit_bpnum``' and \'``$bpnum``' are not equivalent:
  \'``$_hit_bpnum``' is set to the breakpoint number last hit, while
  \'``$bpnum``' is set to the breakpoint number last set.
* If the encountered breakpoint has only one code location, \'``$_hit_locno``'
  is set to 1:

....
Breakpoint 1, main (argc=1, argv=0x7fffffffe018) at zeoes.c:24
24 if (argc > 1)
(gdb) p $_hit_bpnum
$3 = 1
(gdb) p $_hit_locno
$4 = 1
(gdb)
....

* The \'``$_hit_bpnum``' and \'``$_hit_locno``' variables can typically be
  used in a breakpoint command list.
* (see Section 5.1.7 [Breakpoint Command Lists], page 77).
* For example, as part of the breakpoint command list, you can disable
  completely the encountered breakpoint using `_disable $_hit_bpnum_` or
  disable the specific encountered breakpoint location using `_disable
  $_hit_bpnum.$_hit_locno_`.
* If a breakpoint has only one location, \'``$_hit_locno``' is set to 1 and
  the commands `_disable $_hit_bpnum_` and disable `$_hit_bpnum.$_hit_locno`
  both disable the breakpoint.

'''

* You can also define aliases to easily disable the last hit location or last
  hit breakpoint:

....
(gdb) alias lld = disable $_hit_bpnum.$_hit_locno
(gdb) alias lbd = disable $_hit_bpnum
....

=== 5.1.4 Deleting Breakpoints

* It is often necessary to eliminate a breakpoint, watchpoint, or catchpoint
  once it has done its job and you no longer want your program to stop there.
* This is called _deleting the breakpoint_.
* A breakpoint that has been deleted no longer exists; it is forgotten.

'''

* With the `clear` command you can delete breakpoints according to where they
  are in your program.
* With the `delete` command you can delete individual breakpoints,
  watchpoints, or catchpoints by specifying their breakpoint numbers.

'''

* It is not necessary to delete a breakpoint to proceed past it.
* gdb automatically ignores breakpoints on the first instruction to be
  executed when you continue execution without changing the execution address.

=== 5.1.5 Disabling Breakpoints

* Rather than deleting a breakpoint, watchpoint, or catchpoint, you might
  prefer to disable it.
* This makes the breakpoint inoperative as if it had been deleted, but
  remembers the information on the breakpoint so that you can enable it again
  later.

'''

* You disable and enable breakpoints, watchpoints, tracepoints, and
  catchpoints with the `enable` and `disable` commands, optionally specifying
  one or more breakpoint numbers as arguments.
* Use `info break` to print a list of all breakpoints, watchpoints,
  tracepoints, and catchpoints if you do not know which numbers to use.

'''

* Disabling and enabling a breakpoint that has multiple locations affects all
  of its locations.
* A breakpoint, watchpoint, or catchpoint can have any of several different
  states of enablement:
** Enabled. +
   The breakpoint stops your program. +
   A breakpoint set with the `break` command starts out in this state.
** Disabled. +
   The breakpoint has no effect on your program.
** Enabled once. +
   The breakpoint stops your program, but then becomes disabled.
** Enabled for a count. +
   The breakpoint stops your program for the next N times, then becomes
   disabled.
** Enabled for deletion. +
   The breakpoint stops your program, but immediately after it does so it is
   deleted permanently. +
   A breakpoint set with the `tbreak` command starts out in this state.

== 5.4 Signals

* A signal is an asynchronous event that can happen in a program.
* The operating system defines the possible kinds of signals, and gives each
  kind a name and a number.
* For example, in Unix `SIGINT` is the signal a program gets when you type an
  interrupt character (often `_Ctrl-c_`); `SIGSEGV` is the signal a program
  gets from referencing a place in memory far away from all the areas in use;
  `SIGALRM` occurs when the alarm clock timer goes off (which happens only if
  your program has requested an alarm).

'''

* Some signals, including `SIGALRM`, are a normal part of the functioning of
  your program.
* Others, such as `SIGSEGV`, indicate errors; these signals are fatal (they
  kill your program immediately) if the program has not specified in advance
  some other way to handle the signal.
* `SIGINT` does not indicate an error in your program, but it is normally
  fatal so it can carry out the purpose of the interrupt: to kill the program.

'''

* gdb has the ability to detect any occurrence of a signal in your program.
* You can tell gdb in advance what to do for each kind of signal.
* Normally, gdb is set up to let the non-erroneous signals like `SIGALRM` be
  silently passed to your program (so as not to interfere with their role in
  the program's functioning) but to stop your program immediately whenever an
  error signal happens.
* You can change these settings with the `handle` command.

'''

`info signals`::
`info handle`::
* Print a table of all the kinds of signals and how gdb has been told to
  handle each one.
* You can use this to see the signal numbers of all the defined types of
  signals.

`info signals _sig_`::
* Similar, but print information only about the specified signal number.
+
'''
* info handle is an alias for `info signals`.

`catch signal [signal... | 'all']`
* Set a catchpoint for the indicated signals.
* See Section 5.1.3 [Set Catchpoints], page 69, for details about this
  command.

`handle signal [ _signal_ ... ] [_keywords_...]`::
* Change the way gdb handles each _signal_.
* Each _signal_ can be the number of a signal or its name (with or without the
  \'``SIG``' at the beginning); a list of signal numbers of the form
  \'``low-high``'; or the word \'``all``', meaning all the known signals,
  except `SIGINT` and `SIGTRAP`, which are used by gdb.
* Optional argument _keywords_, described below, say what changes to make to
  all of the specified signals.

'''

* The keywords allowed by the `handle` command can be abbreviated.
* Their full names are:

'''

`nostop`::
* gdb should not stop your program when this signal happens.
* It may still print a message telling you that the signal has come in.

`stop`::
* gdb should stop your program when this signal happens.
* This implies the `print` keyword as well.

`print`::
* gdb should print a message when this signal happens.

`noprint`::
* gdb should not mention the occurrence of the signal at all.
* This implies the `nostop` keyword as well.

`pass`::
`noignore`::
* gdb should allow your program to see this signal; your program can handle
  the signal, or else it may terminate if the signal is fatal and not handled.
* `pass` and `noignore` are synonyms.

`nopass`::
`ignore`::
* gdb should not allow your program to see this signal.
* `nopass` and `ignore` are synonyms.

'''

* When a signal stops your program, the signal is not visible to the program
  until you continue.
* Your program sees the signal then, if `pass` is in effect for the signal in
  question at that time.
* In other words, after gdb reports a signal, you can use the `handle` command
  with `pass` or `nopass` to control whether your program sees that signal
  when you continue.

'''

* The default is set to `nostop`, `noprint`, `pass` for non-erroneous signals
  such as `SIGALRM`, `SIGWINCH` and `SIGCHLD`, and to `stop`, `print`, `pass`
  for the erroneous signals.

'''

* You can also use the `signal` command to prevent your program from seeing a
  signal, or cause it to see a signal it normally would not see, or to give it
  any signal at any time.
* For example, if your program stopped due to some sort of memory reference
  error, you might store correct values into the erroneous variables and
  continue, hoping to see more execution; but your program would probably
  terminate immediately as a result of the fatal signal once it saw the
  signal.
* To prevent this, you can continue with \'``signal 0``'.
* See Section 17.3 [Giving your Program a Signal], page 279.

'''

* gdb optimizes for stepping the mainline code.
* If a signal that has `handle nostop` and `handle pass` set arrives while a
  stepping command (e.g., `stepi`, `step`, `next`) is in progress, gdb lets
  the signal handler run and then resumes stepping the mainline code once the
  signal handler returns.
* In other words, gdb steps over the signal handler.
* This prevents signals that you've specified as not interesting (with `handle
  nostop`) from changing the focus of debugging unexpectedly.
* Note that the signal handler itself may still hit a breakpoint, stop for
  another signal that has `handle stop` in effect, or for any other event that
  normally results in stopping the stepping command sooner.
* Also note that gdb still informs you that the program received a signal if
  `handle print` is set.

'''

* If you set `handle pass` for a signal, and your program sets up a handler
  for it, then issuing a stepping command, such as `step` or `stepi`, when
  your program is stopped due to the signal will step into the signal handler
  (if the target supports that).

'''

* Likewise, if you use the `queue-signal` command to queue a signal to be
  delivered to the current thread when execution of the thread resumes (see
  Section 17.3 [Giving your Program a Signal], page 279), then a stepping
  command will step into the signal handler.

'''

* Here's an example, using `stepi` to step to the first instruction of
  `SIGUSR1`'s handler:

....
(gdb) handle SIGUSR1
Signal	Stop	Print	Pass to program	Description
SIGUSR1	Yes	Yes	Yes		User defined signal 1
(gdb) c
Continuing.
Program received signal SIGUSR1, User defined signal 1.
main () sigusr1.c:28
28 p = 0;
(gdb) si
sigusr1_handler () at sigusr1.c:9
9 {
....

* The same, but using `queue-signal` instead of waiting for the program to
  receive the signal first:

....
(gdb) n
28 p = 0;
(gdb) queue-signal SIGUSR1
(gdb) si
sigusr1_handler () at sigusr1.c:9
9 {
(gdb)
....

'''

* On some targets, gdb can inspect extra signal information associated with
  the intercepted signal, before it is actually delivered to the program being
  debugged.
* This information is exported by the convenience variable `$_siginfo`, and
  consists of data that is passed by the kernel to the signal handler at the
  time of the receipt of a signal.
* The data type of the information itself is target dependent.
* You can see the data type using the `ptype $_siginfo` command.
* On Unix systems, it typically corresponds to the standard `siginfo_t` type,
  as defined in the `signal.h` system header.

'''

* Here's an example, on a gnu/Linux system, printing the stray referenced
  address that raised a segmentation fault.

....
(gdb) continue
Program received signal SIGSEGV, Segmentation fault.
0x0000000000400766 in main ()
69 *(int *)p = 0;
(gdb) ptype $_siginfo
type = struct {
	int si_signo;
	int si_errno;
	int si_code;
	union {
		int _pad[28];
		struct {...} _kill;
		struct {...} _timer;
		struct {...} _rt;
		struct {...} _sigchld;
		struct {...} _sigfault;
		struct {...} _sigpoll;
	} _sifields;
}
(gdb) ptype $_siginfo._sifields._sigfault
type = struct {
	void *si_addr;
}
(gdb) p $_siginfo._sifields._sigfault.si_addr
$1 = (void *) 0x7ffff7ff7000
....

* Depending on target support, `$_siginfo` may also be writable.
